name: login_with_laravel_api
description: A new Flutter project.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.6
  dio: ^5.1.2
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  platform_device_id: ^1.0.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  smooth_page_indicator: ^1.1.0
  flutter_feather_icons: ^2.0.0+1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
